### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#356]
https://projects.invisionapp.com/d/main#/console/11107725/235445415/preview

Meet with Anthony to discuss where he left off with the dashboard development.

Remaining Features to Complete:

- [x] Hovering on "..." icon in a block will bring up a menu for the rest of the options: https://projects.invisionapp.com/d/main#/console/11107725/235445415/preview

- [x] Ability to Edit Dashboard: https://projects.invisionapp.com/d/main#/console/11107725/242713069/preview
  - [x] Dashboard goes into "edit mode" after user selects the Edit Dashboard button.
  - [x] Ability to Create, Edit, Move around and Delete Sections.
    - [x] Deleteing a section will cause the blocks within the section to fall into the section above. This functionality is based off of how InVision organizes screens into sections.
  - [x] Ability to hover over a block in edit mode to reveal edit / delete options. 
  - [x] Ability to Edit a block, and according edit block modal: https://projects.invisionapp.com/d/main#/console/11107725/327005040/preview
  - [x] Ability to Drag blocks around to reorganize them
  - [x] Ability to Delete a block. Selecting the trash icon will bring up a small delete modal
  - [x] Ability to Edit / Reorganize Quick Actions and according Modal: https://projects.invisionapp.com/d/main#/console/11107725/242718620/preview
  - [x] Ability to finish editing dashboard to save changes

---
- [x] Finalization of Fun Blocks
  - [x] Note Block, with the ability to edit title and text
  - [x] Inspirational Quote block. Ask anthony on how to implement, functionality of quotes is built into laravel.
  - [x] Twitter Block. Will just be a twitter widget of the Kora3 Twitter feed (https://twitter.com/kora_matrix) using twitters official widget.

**Comment by fritosxii** [comment]
I started the ability to add blocks of differnt types. Most the work left is modification of pages, and general editing of dashboards. Let me know if you have questions on block types

**Comment by suuuth** [comment]
branch suth-356

**Comment by suuuth** [comment]
What should the behavior be if the user tries to delete the last remaining section on the dashboard?  Should I prevent this from happening by removing the `delete-section` button when there's only 1 section left, or delete the section along with its blocks?

**Comment by austintruchan** [comment]
Ideally it will let you delete all sections if thats what the user wants to do. If the user deletes the last section, it should not delete any blocks. Deleting any section will ideally not delete it's according blocks, but will have the blocks within move up into the section above.

**Comment by fritosxii** [comment]
@suuuth So you are aware the only fun block that is not implemented is the tiwtter one. We will probably move this to a new issue for the future

**Comment by austintruchan** [comment]
## General Fixes
- [ ] Unable to move my mouse up to the options before they disappear, when hovering on the “ooo” icon. These should be selectable options that take you to those according pages. 
<img width="237" alt="screen shot 2018-11-09 at 11 12 59 am" src="https://user-images.githubusercontent.com/5408529/48274078-88c4ab00-e410-11e8-9f2e-2ea155a6e4ca.png">

- [ ] When the sidebar is open, have the same responsiveness of the blocks that there is when the sidebar isn’t open, where the columns expand to full width. 

- [ ] Add tooltips for these buttons on hover for “Add New Block” and “Edit Dashboard” 
<img width="166" alt="screen shot 2018-11-09 at 11 24 27 am" src="https://user-images.githubusercontent.com/5408529/48274793-19e85180-e412-11e8-9c50-ab222a4bdf73.png">

- [ ] Make sure Add a New Block and Select to Finish Editing are Ubuntu Medium
<img width="496" alt="screen shot 2018-11-09 at 11 29 36 am" src="https://user-images.githubusercontent.com/5408529/48275245-0be70080-e413-11e8-9310-2fc58d76655d.png">

- [ ] Block titles that are links seem to have a font weight on them. Should just be Ubuntu Medium 
<img width="226" alt="screen shot 2018-11-09 at 11 43 00 am" src="https://user-images.githubusercontent.com/5408529/48275903-b4e22b00-e414-11e8-920a-74b634dc8355.png">


## Add New Dashboard Block
- [ ] If possible update the placeholders for block type to “Select a block type”, and update the placeholder for Add to Section to “Select a section to add to” 

- [ ] List projects and form items alphabetically, and records numerically. (Should listed the same within the edit modal as well)


## Editing Dashboard
- [ ] after completing edit actions, like editing a block, deleting a block, creating a new section, etc., keep the dashboard in edit mode if possible. User will select the finish editing dashboard button in order to go back to the regular dashboard. 

- [ ] When editing a section title, make it so that you can make an edit without having the title delete itself upon editing. If possible. 

- [ ] Update arrow icons for the section up and down to these icons. They currently have the wrong proportions since they need to be bigger in this case: 

- [ ] Add tooltips for the edit section icons. “Move Section Down”, “Move Section Up”, “Delete Section” 

## Quick Edit Options Modal
- [ ] Make sure options below the line in the edit quick options can be reorganized.
- [ ] Remove underline from quick option titles on hover
<img width="811" alt="screen shot 2018-11-09 at 11 10 44 am" src="https://user-images.githubusercontent.com/5408529/48273986-4d29e100-e410-11e8-8ec0-4ab73ba4520a.png">
 

## Note Block
- [ ] I should be able to edit the title or body without having the entire note erase itself after each edit.
- [ ] Editing the note blocks content from within its edit block modal doesn’t seem to work properly. Edits don’t seem to go through from this modal.

**Comment by suuuth** [comment]
Creating a new block will need a page refresh for the user to see.  But everything I believe I can make functional without needing a page refresh.

Also, I am not sure what the 'other options' are supposed to be for the Form blocks.  Currently the 'ooo' tooltip just contains the same thing that you can see on a Project block.  Let me know if/what I should change this to @austintruchan

**Comment by austintruchan** [comment]
if we are talking about ...

> " after completing edit actions, like editing a block, deleting a block, creating a new section, etc., keep the dashboard in edit mode if possible. User will select the finish editing dashboard button in order to go back to the regular dashboard"

 ... page refreshes are fine. I just want the mode to remain in the edit mode until the user clicks one of the finish editing buttons.



The other options for form blocks will be all of the options that are in the sidebar for a single form, assuming the user is an admin. 

- [ ] Thinking of this, we should also stop users that aren't project admins from seeing admin options in project blocks,  and the same if they arent form admins for form blocks. So some project / form blocks they'll see admin options if they're an admin to the project / form, and project / form blocks that they aren't an admin of they won't be able to see admin options. 

- [ ] Update tooltips for all icons so they're centered above their icons on hover.

- [ ] For the options in the "edit quick actions" modal, all options should be able to moved above or below the line. Items that are below the line can be moved up, pushing another option down below the line so the user can customize which options display and which display in the "ooo" option.

- [ ] On mobile, make sure the blocks expand to be full width, looks like there is too much space to the left and right of the blocks on small widths. 

- [ ] For note blocks, I am able to make the title as long as I want it to be. Lets cap it at 40 characters. Update the create block modal to be 40 characters as well.

- [ ] For the note block, If I add a ton of text to the body, the text becomes scrollable, this is good. However upon page reload the note then appears to be blank.

**Comment by austintruchan** [comment]
Just realized you didn't have this in "Ready for Review", but i have reviewed where it is at.

**Comment by austintruchan** [comment]
- [ ] Update the various little icons that need updating. I have added several new icons under the dashboard section on this invision page: https://projects.invisionapp.com/d/main#/console/11107725/250455416/inspect

**Comment by austintruchan** [comment]
- [ ] If possible, keep the blue edit overlay on hover when editing long note blocks remain in proper position if the note block is scrolled. Not a huge issue but if you can fix, great!
<img width="535" alt="screen shot 2018-11-16 at 10 50 29 am" src="https://user-images.githubusercontent.com/5408529/48631898-925c8e80-e98d-11e8-9b73-cfe1f1072739.png">

- [ ] Editing notes directly when the block seems fine, but editing them from their edit modals doesn't seem to work. The description field in the modal also seems to have a cap. 

- [ ] can we make it possible to drag blocks to different sections in edit mode?

- [ ] Some weird spacing issues at the bottom of dashboard. THe block seems to not be apart of any section, and moving a section below a block not a part of a section creates a large space. I would just make it so that all blocks are apart of a section, except for blocks that sit above the first listed section

**Comment by austintruchan** [comment]
- [ ] Can't seem to move blocks into sections that don't have any blocks already.
- [ ] Also if possible, see if we can move blocks up above the first section so that they then sit in no section.
- [ ] Deleting first section, which contained blocks, is good, but the layout of the blocks got weird: 
<img width="813" alt="screen shot 2018-11-28 at 12 03 02 pm" src="https://user-images.githubusercontent.com/5408529/49168520-a85f3d00-f305-11e8-9e4f-b91714e2eb9f.png">

- [ ] Things get weirder when you try and move the next section up and above these blocks: 
<img width="823" alt="screen shot 2018-11-28 at 12 04 41 pm" src="https://user-images.githubusercontent.com/5408529/49168670-02f89900-f306-11e8-804c-3fc889566347.png">

See if you can fix this weirdness, otherwise we can discuss and make it so that blocks have to exist in a section. 

- [ ] Include cursor:pointer on the entire quick action bar/card within the edit quick actions modal. 
- [ ] Is is possible to update the quick actions list in the edit quick actions modal so that if you move one option from below the line, to above the line, the last option that was above the line now moves below the line? I see that it does update after "update quick actions" and reopening the modal, but would be great if this happened in real time. 

- [ ] Reduce the margin between the note title and the note content down to 10px. 

- [ ] Lets remove the quick search bar in the dashboard block type dropdown. 
<img width="699" alt="screen shot 2018-11-28 at 11 56 25 am" src="https://user-images.githubusercontent.com/5408529/49168042-b2347080-f304-11e8-9159-459e549d7c4e.png">

- [ ] In the add new dashboard block "Select a ... " input, if possible, update the placeholder to be dynamic depending on the selected block type. So for "Select Form" it would be "Select a form"
<img width="362" alt="screen shot 2018-11-28 at 11 57 25 am" src="https://user-images.githubusercontent.com/5408529/49168170-f32c8500-f304-11e8-8131-d50d0341df6c.png">

- [ ] Delete block modal title should be left aligned: 
<img width="355" alt="screen shot 2018-11-28 at 12 00 10 pm" src="https://user-images.githubusercontent.com/5408529/49168327-3e469800-f305-11e8-91c3-1c891079afb1.png">

- [ ] Delete block modal body text should also be ubuntu regular.

**Comment by suuuth** [comment]
> Its impossible to create a block if no sections exist.

Does this mean you were not able to create a block when no sections exist?  Or does it mean that you want me to prevent users from creating a block when no sections exist?  Just want to be sure I understand you correctly. @austintruchan

**Comment by austintruchan** [comment]
Okay. I am able to add blocks to the No Section now.

**Comment by suuuth** [comment]
Okay this should be good to go.  I made it a little easier to drop blocks into sections that don't already have blocks.  What was initially causing issues was the fact that, when no blocks were present, the block container (the thing that needs to be present for you to drop blocks) had a height of 0px.  Essentially there wasn't anything to drop the block into.  I corrected this by giving the element a `min-height: 10px;`.  However this seemed to be too small, as you noted, so I increased this `min-height` value to `50px`, and adjusted margins to preserve the total height of the section.  These margins automatically adjust when you drop a block in an empty section, or drag all blocks out of a section.

**Comment by austintruchan** [comment]
Ok! Yes, it is much easier to add blocks into sections that don't already have blocks now. 

- [ ] I'm still unable to immediately drag and drop blocks into newly created sections though. After a page refresh the blocks can be moved into the new section though. However it would be great if I could immediately move them in after creating the new section.

**Comment by suuuth** [comment]
Fixed! `.sortable()` is weird but this is working reliably for me now

**Comment by austintruchan** [comment]
Bravo!! You did it!! Almost...

- [ ] So I went to test out a fresh dashboard as someone other than admin. This is where I am unable to to add any new blocks, because the "No section" does not exist in the "Add to section" dropdown. So if you sign in as a different user, and try to add a block on a blank dashboard, I am unable to.

**Comment by austintruchan** [comment]
- [ ] We also want to update the dashboard dropdown in the top navigation and in the side bar to simply just be a button that takes the user to the dashboard.

**Comment by suuuth** [comment]
Fixed the issue with new users not being able to add blocks to a fresh dashboard.  The nav dropdown for 'dashboard' is now just a button that take the user directly to the dashboard, with the option to remove this button with the user's 'use dashboard' preference

**Comment by austintruchan** [comment]
- [ ] So with the dashboard button in the top nav, I realized that items that have the dropdown arrow are maybe 1px too low. If you add padding-bottom: 1px; to their spans it looks perfect. In this image you can see how projects looks lower than dashboard. 
<img width="185" alt="screen shot 2018-12-03 at 3 53 51 pm" src="https://user-images.githubusercontent.com/5408529/49401292-bc93a780-f714-11e8-90ac-09efbaf3bea2.png">

- [ ] When dragging blocks in edit mode, if you grab the block by the "Edit Block" button, it will also drag the entire section with the block, instead of just the block.

**Comment by suuuth** [comment]
The dragging issue was odd, thankfully stackexchange had a solution.  The spacing issue just ended up being a css/javascript issue, which was fixed with a quick refactor.  This should be good for another review now.

**Comment by austintruchan** [comment]
I think all looks good for now!
